"""Domain models for VisionOps.

These Pydantic models define the structured state that flows through
the agent graph. All VLM outputs are validated against these models.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Concept Extraction
# ---------------------------------------------------------------------------

class Concept(BaseModel):
    """A meaningful concept extracted from a technical document."""

    id: str = Field(..., description="Unique identifier for the concept")
    name: str = Field(..., description="Human-readable concept name")
    description: str = Field(..., description="Brief description of the concept")
    role: str | None = Field(default=None, description="Role in the system (e.g. processing_component)")
    equations: list[str] = Field(default_factory=list, description="Related equation IDs")
    importance: float | None = Field(default=None, ge=0.0, le=1.0, description="Importance score 0-1")


# ---------------------------------------------------------------------------
# Relationships
# ---------------------------------------------------------------------------

class Relationship(BaseModel):
    """A relationship between two concepts."""

    source: str = Field(..., description="Source concept ID")
    target: str = Field(..., description="Target concept ID")
    relationship: str = Field(..., description="Relationship type (e.g. produces, feeds_into)")
    direction: str = Field(
        ...,
        description="Direction: forward, backward, or bidirectional",
    )
    explanation: str | None = Field(default=None, description="Human-readable explanation")


# ---------------------------------------------------------------------------
# Equations
# ---------------------------------------------------------------------------

class Equation(BaseModel):
    """A mathematical equation extracted from a document."""

    id: str = Field(..., description="Unique equation identifier")
    expression: str = Field(..., description="The equation expression")
    description: str = Field(..., description="What this equation represents")
    related_concepts: list[str] = Field(default_factory=list, description="Related concept IDs")
    importance: float = Field(..., ge=0.0, le=1.0, description="Importance score 0-1")


# ---------------------------------------------------------------------------
# Diagram Specification
# ---------------------------------------------------------------------------

class DiagramNode(BaseModel):
    """A node in the diagram specification."""

    id: str = Field(..., description="Unique node identifier")
    label: str = Field(..., description="Display label for the node")
    description: str | None = Field(default=None, description="Node description")
    type: str = Field(default="component", description="Node type: component, input, output, process")


class DiagramEdge(BaseModel):
    """An edge in the diagram specification."""

    source: str = Field(..., description="Source node ID")
    target: str = Field(..., description="Target node ID")
    label: str | None = Field(default=None, description="Edge label")
    direction: str = Field(default="forward", description="Direction: forward, backward, bidirectional")


class DiagramSpec(BaseModel):
    """Structured diagram specification generated by the VLM.

    This is consumed by the deterministic renderer to produce SVG.
    The VLM must NOT generate SVG directly — only this specification.
    """

    title: str = Field(..., description="Diagram title")
    nodes: list[DiagramNode] = Field(..., description="Diagram nodes")
    edges: list[DiagramEdge] = Field(..., description="Diagram edges")
    layout: str = Field(default="flowchart", description="Layout type: flowchart, sequence")

    def get_node_ids(self) -> set[str]:
        """Return set of all node IDs."""
        return {node.id for node in self.nodes}

    def validate_edge_references(self) -> list[str]:
        """Return list of edge reference errors."""
        node_ids = self.get_node_ids()
        errors = []
        for edge in self.edges:
            if edge.source not in node_ids:
                errors.append(f"Edge source '{edge.source}' references unknown node")
            if edge.target not in node_ids:
                errors.append(f"Edge target '{edge.target}' references unknown node")
        return errors


# ---------------------------------------------------------------------------
# Critique
# ---------------------------------------------------------------------------

class Critique(BaseModel):
    """Structured critique of a generated diagram by the visual critic."""

    passed: bool = Field(..., description="Whether the diagram passes quality check")
    score: float = Field(..., ge=0.0, le=1.0, description="Diagnostic quality score 0-1")
    missing_concepts: list[str] = Field(default_factory=list)
    incorrect_relationships: list[str] = Field(default_factory=list)
    incorrect_direction: list[str] = Field(default_factory=list)
    missing_equations: list[str] = Field(default_factory=list)
    visual_issues: list[str] = Field(default_factory=list)
    complexity_issues: list[str] = Field(default_factory=list)
    suggested_changes: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Agent State
# ---------------------------------------------------------------------------

class VisionOpsState(BaseModel):
    """Complete state for a VisionOps analysis run.

    This is the typed state that flows through the LangGraph agent graph.
    """

    run_id: str = Field(..., description="Unique run identifier")
    skill: str = Field(..., description="Skill name (e.g. technical_document_to_diagram)")

    # Input
    input_document: str | None = Field(default=None, description="Path to uploaded document")
    page_images: list[str] = Field(default_factory=list, description="Paths to extracted page images")

    # Extraction Results
    concepts: list[Concept] = Field(default_factory=list)
    relationships: list[Relationship] = Field(default_factory=list)
    equations: list[Equation] = Field(default_factory=list)

    # Diagram
    diagram_spec: DiagramSpec | None = Field(default=None)
    rendered_diagram: str | None = Field(default=None, description="Path to rendered SVG")

    # Critique
    critique: Critique | None = Field(default=None)

    # Iteration Control
    iteration: int = Field(default=0, description="Current refinement iteration")
    max_iterations: int = Field(default=2, description="Maximum refinement iterations")

    # Explanation
    explanation: str | None = Field(default=None)

    # Status
    status: str = Field(default="pending", description="pending, running, completed, failed")
    errors: list[str] = Field(default_factory=list)
